// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1w0_E1z-dWAKh345bNV_NidH5cas5p-0',
    appId: '1:341650802402:android:9233025b512029ddaa00bb',
    messagingSenderId: '341650802402',
    projectId: 'flash-app-41927',
    databaseURL: 'https://flash-app-41927-default-rtdb.firebaseio.com',
    storageBucket: 'flash-app-41927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HRwvMzrzYOK22gHfx0jFwbzGg4Lf5zk',
    appId: '1:341650802402:ios:4a2920b61c4036ddaa00bb',
    messagingSenderId: '341650802402',
    projectId: 'flash-app-41927',
    databaseURL: 'https://flash-app-41927-default-rtdb.firebaseio.com',
    storageBucket: 'flash-app-41927.appspot.com',
    iosClientId: '341650802402-c44e7fc9m6jebhqt118apb8seg6cul9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7HRwvMzrzYOK22gHfx0jFwbzGg4Lf5zk',
    appId: '1:341650802402:ios:4a2920b61c4036ddaa00bb',
    messagingSenderId: '341650802402',
    projectId: 'flash-app-41927',
    databaseURL: 'https://flash-app-41927-default-rtdb.firebaseio.com',
    storageBucket: 'flash-app-41927.appspot.com',
    iosClientId: '341650802402-c44e7fc9m6jebhqt118apb8seg6cul9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
